"""
Admin Token Setup Script
=========================
One-time setup to configure encrypted tokens.

Usage:
    python setup-tokens.py

This script will:
1. Generate encryption key (if needed)
2. Encrypt your GitHub tokens
3. Save to secure file
4. Create .env file with configuration
"""

import os
import json
from cryptography.fernet import Fernet
import getpass

def setup_encryption_key():
    """Generate or load encryption key"""
    if os.path.exists('.env'):
        # Check if SECRET_KEY exists
        with open('.env', 'r') as f:
            for line in f:
                if line.startswith('SECRET_KEY='):
                    key = line.split('=', 1)[1].strip()
                    print("✅ Using existing encryption key from .env")
                    return key
    
    # Generate new key
    key = Fernet.generate_key().decode()
    print("🔑 Generated new encryption key")
    return key

def encrypt_tokens(tokens, key):
    """Encrypt list of tokens"""
    cipher = Fernet(key.encode())
    tokens_json = json.dumps(tokens)
    encrypted = cipher.encrypt(tokens_json.encode()).decode()
    return encrypted

def save_env_file(secret_key, admin_password, port=5000, origins='*'):
    """Save .env configuration file"""
    env_content = f"""# Secure GitHub API Proxy Configuration
# Generated by setup-tokens.py

# Encryption key (DO NOT SHARE!)
SECRET_KEY={secret_key}

# Admin password for token management
ADMIN_PASSWORD={admin_password}

# Server configuration
PORT={port}

# Allowed CORS origins (comma-separated)
ALLOWED_ORIGINS={origins}

# Debug mode
DEBUG=False
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ Saved .env configuration file")

def main():
    print("\n" + "="*70)
    print("🔐 SECURE TOKEN SETUP - Admin Configuration")
    print("="*70 + "\n")
    
    # Step 1: Get encryption key
    secret_key = setup_encryption_key()
    
    # Step 2: Get admin password
    print("\n📝 Set Admin Password")
    print("This password will be used to manage tokens via admin portal.")
    admin_password = getpass.getpass("Enter admin password: ")
    confirm_password = getpass.getpass("Confirm admin password: ")
    
    if admin_password != confirm_password:
        print("❌ Passwords don't match. Exiting.")
        return
    
    if len(admin_password) < 8:
        print("⚠️  Warning: Password should be at least 8 characters for security.")
        proceed = input("Continue anyway? (y/n): ")
        if proceed.lower() != 'y':
            return
    
    # Step 3: Get GitHub tokens
    print("\n🔑 Add GitHub Tokens")
    print("Enter your GitHub Personal Access Tokens (one per line).")
    print("Press Enter twice when done.\n")
    
    tokens = []
    while True:
        token = getpass.getpass(f"Token {len(tokens) + 1} (or press Enter to finish): ")
        if not token:
            if len(tokens) == 0:
                print("⚠️  No tokens entered. Continue without tokens? (public mode only)")
                proceed = input("Continue? (y/n): ")
                if proceed.lower() == 'y':
                    break
                else:
                    continue
            break
        
        # Basic validation
        if len(token) < 20:
            print("⚠️  Token seems too short. GitHub tokens are usually 40+ characters.")
            continue
        
        tokens.append(token)
        print(f"✅ Token {len(tokens)} added")
    
    # Step 4: Encrypt and save tokens
    if tokens:
        encrypted_data = encrypt_tokens(tokens, secret_key)
        
        with open('tokens.enc', 'w') as f:
            f.write(encrypted_data)
        
        print(f"\n✅ Encrypted and saved {len(tokens)} tokens to tokens.enc")
        print(f"⚡ Effective rate limit: {len(tokens) * 5000} requests/hour")
    
    # Step 5: Server configuration
    print("\n🌐 Server Configuration")
    port = input("Server port (default 5000): ").strip() or "5000"
    
    print("\nAllowed CORS origins (for frontend access)")
    print("Examples: http://localhost:8000, https://yourdomain.com")
    origins = input("Enter origins (comma-separated, or * for all): ").strip() or "*"
    
    # Step 6: Save .env file
    save_env_file(secret_key, admin_password, port, origins)
    
    # Summary
    print("\n" + "="*70)
    print("✅ SETUP COMPLETE!")
    print("="*70)
    print(f"🔑 Tokens configured: {len(tokens)}")
    print(f"⚡ Rate limit: {len(tokens) * 5000 if tokens else 60} req/hour")
    print(f"📡 Server port: {port}")
    print(f"🌐 CORS origins: {origins}")
    print(f"🔒 Admin password: {'*' * len(admin_password)} (saved)")
    print("="*70)
    
    print("\n📌 Next Steps:")
    print("1. Start server: python secure-proxy-server.py")
    print("2. Test health: http://localhost:" + port + "/health")
    print("3. Configure frontend to use proxy")
    print("\n🔐 Admin Portal Access:")
    print("   - Upload more tokens via only-boss-dashboard.html")
    print("   - Use admin password to authenticate")
    
    print("\n⚠️  SECURITY NOTES:")
    print("   - Keep .env file SECRET (add to .gitignore)")
    print("   - Keep tokens.enc file SECRET")
    print("   - Never commit these files to git!")
    
    # Create .gitignore
    gitignore_content = """# Security - Never commit these!
.env
tokens.enc
*.pyc
__pycache__/
"""
    
    with open('.gitignore', 'w') as f:
        f.write(gitignore_content)
    
    print("\n✅ Created .gitignore to protect sensitive files")
    print("\n🎉 You're all set! Start the server and enjoy unlimited API access!\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
